### ISSUE TITLE
NaN

### ISSUE THREAD

**Issue by harrisosserman** [harrisosserman/word2vec#2]
- [x] Make sure that I should be initializing my matrices at [-1, 1]
- [ ]  Make sure that my optimizing algorithm is correct
- [x]  Make sure that my corpus is good (test with wikipedia corpus)
- [x]  Add a test to make sure that I am initializing the matrices correctly
- [x]  Look for scaling requirements for handling frequent/infrequent words
- [x]  Investigate if there is a maximum frequency that I should be using for my most frequent words
- [x] Include actual word in the md5 hashing algorithm

**Comment by harrisosserman** [comment]
From reading the C code, it seems like I should be initializing all of the entries to be 0 instead of [-1, 1]

**Comment by harrisosserman** [comment]
According to this paper, deleting rare words has negligible improvement on performance: https://levyomer.files.wordpress.com/2015/03/improving-distributional-similarity-tacl-2015.pdf

**Comment by sisirkoppaka** [comment]
What about the frequent words, stop words?

**Comment by harrisosserman** [comment]
@sisirkoppaka just realized that I forgot to tell you how I handled frequent words/stop words.  Here is where I introduced subsampling.  The probability that I randomly remove a word from the corpus is directly correlated with how often the word shows up in the corpus 😄 
https://github.com/harrisosserman/word2vec/commit/8c37ea7d54cc9f9ac134f8b55231dac17f1e873c

**Comment by sisirkoppaka** [comment]
Ah, that's not what should be happening!
